Feature/query update
thasipablo/Vet-Clinic pull request #2
Opened 2023-09-28 16:20 UTC by thasipablo

**In this project**:

I use transactions to update and delete records. I also use aggregation functions and GROUP BY to answer analytical questions.
Find screenshots of all queries bellow:

**Section 1:**
![01](https://github.com/thasipablo/Vet-Clinic/assets/39631185/79f26ebf-6f4f-45d5-a320-998296f65cb1)
![02](https://github.com/thasipablo/Vet-Clinic/assets/39631185/7a694f2d-a6d4-4f62-a75d-6228740e09ff)
![03](https://github.com/thasipablo/Vet-Clinic/assets/39631185/430ba5ed-b649-477f-9d14-e330bea48c0a)
![04](https://github.com/thasipablo/Vet-Clinic/assets/39631185/333be787-518f-4d9a-9313-d824fdb1c0af)

**Section 2:**

2023-09-28 21:53 UTC, V-Blaze requested changes
## Hi @thasipablo 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Correct Gitflow✔
- Most queries written correctly 👋 
-  Some data inserted correctly into the database ✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 21:53 UTC, V-Blaze commented on schema.sql
>    neutered BOOLEAN,
- You have done well so far :+1: :+1: But there are a few changes and requirements you need to meet before moving to the next milestone. :+1: :waffle: 

- [ ] When working with databases, you don't edit an already existing table to add or remove a column in a table, you add a line of SQL to do that. In this case, you are not meant to edit the animal table and add the `species` column, you rather need to do it this way.
```sh
ALTER TABLE animals ADD species varchar(100);
```
I suggest you update your schema file accordingly. :wave: :smile:

2023-09-28 21:53 UTC, V-Blaze commented on data.sql
> +  ('Ditto', '2022-05-14', 22, true, 4, 'pokemon');
- [ ] Looking at your `data.sql` file, I you do not seem to have all the data in the project requirement here. you only added one. I'll suggest you go through the requirement one more time and fill up all the provided data here. :smile: :wave: 

- - Screenshot reference:
![Selection_010](https://github.com/thasipablo/Vet-Clinic/assets/107632780/29fb38f6-f907-4df9-b2ec-d9b9ddbbceb4)

- [ ] Also Looking at the project requirements, species were not provided here for any of the animals, I'll suggest you remove the `pokemon` species you added to `Ditto` as it will affect the result of the queries..

2023-09-28 21:53 UTC, V-Blaze commented on queries.sql
> +SELECT * FROM animals;
>Inside a transaction update the animals' table by setting the species column to unspecified. Verify that the change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.

- [ ] According to the project requirement, after setting the species column to `unspecified`, you need to verify that the changes were made and also include a query for that before the `ROLLBACK`. I suggest you update this query to include the verifications. here's what it should look like. :+1: :+1: 

```sh
   BEGIN;
   UPDATE animals
   SET species = 'unspecified';
   SELECT species from animals; 
   ROLLBACK;
   SELECT species from animals;
```

2023-09-28 21:53 UTC, V-Blaze commented on queries.sql
> +ROLLBACK;
- [ ] Just as I pointed out above about verifying the changes and having a code for that, according to the requirement, after the `ROLLBACK` here, you need to verify that the changes where not successful. I'll suggest you update your code to reflect that. :small_airplane: :wave:

2023-09-28 21:53 UTC, V-Blaze commented on data.sql
>  INSERT INTO animals (
## I noticed that in your `data.sql` and `queries.sql`, you deleted the codes from the previous milestone. This is a continuum of the project and therefore, it's not advisable to clear your codes, you were meant to continue writing your codes below the existing code from the previous milestones. I suggest you bring back those codes and leave them above these current ones in their respective files. :wave: :wave: :100:

2023-09-28 22:15 UTC, thasipablo commented
Thank you @V-Blaze . All is fixed

2023-09-29 00:01 UTC, Whoistolu reviewed
Hi @thasipablo 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly remove the Run test section of the README since the commands to run the tests are not available and it is not a requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-29 07:11 UTC, thasipablo commented
Thank you @Whoistolu . The `Run tests` section is removed from the readme file.

2023-09-29 07:19 UTC, mukhammadrizooff approved these changes
Hi @thasipablo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 08:03 UTC, merged